### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by Epharim112** [nilgradisnik/coinprice-indicator#110]
Traceback (most recent call last):
  File "/opt/coindicator/venv/bin/./coindicator", line 8, in <module>
    sys.exit(main())
  File "/opt/coindicator/venv/lib/python3.10/site-packages/coin/coin.py", line 354, in main
    Coin(config)
  File "/opt/coindicator/venv/lib/python3.10/site-packages/coin/coin.py", line 57, in __init__
    self._load_settings()
  File "/opt/coindicator/venv/lib/python3.10/site-packages/coin/coin.py", line 125, in _load_settings
    "asset_pair": self.assets[first_code][0].get("pair"),
IndexError: list index out of range

lager version

python3.10/site-packages/coin/exchanges/unocoin.py
# code object from '/opt/coindicator/venv/lib/python3.10/site-packages/coin/exchanges/__pycache__/unocoin.cpython-310.pyc'
import 'coin.exchanges.unocoin' # <_frozen_importlib_external.SourceFileLoader object at 0x77d50958ff70>
# /usr/lib/python3.10/__pycache__/netrc.cpython-310.pyc matches /usr/lib/python3.10/netrc.py
# code object from '/usr/lib/python3.10/__pycache__/netrc.cpython-310.pyc'
# /usr/lib/python3.10/__pycache__/shlex.cpython-310.pyc matches /usr/lib/python3.10/shlex.py
# code object from '/usr/lib/python3.10/__pycache__/shlex.cpython-310.pyc'
import 'shlex' # <_frozen_importlib_external.SourceFileLoader object at 0x77d5095d4ac0>
import 'netrc' # <_frozen_importlib_external.SourceFileLoader object at 0x77d5095d47f0>
Traceback (most recent call last):
  File "/opt/coindicator/venv/bin/./coindicator", line 8, in <module>
    sys.exit(main())
  File "/opt/coindicator/venv/lib/python3.10/site-packages/coin/coin.py", line 354, in main
    Coin(config)
  File "/opt/coindicator/venv/lib/python3.10/site-packages/coin/coin.py", line 57, in __init__
    self._load_settings()
  File "/opt/coindicator/venv/lib/python3.10/site-packages/coin/coin.py", line 125, in _load_settings
    "asset_pair": self.assets[first_code][0].get("pair"),
IndexError: list index out of range
# /opt/coindicator/venv/lib/python3.10/site-packages/pygame/__pycache__/freetype.cpython-310.pyc matches /opt/coindicator/venv/lib/python3.10/site-packages/pygame/freetype.py
# code object from '/opt/coindicator/venv/lib/python3.10/site-packages/pygame/__pycache__/freetype.cpython-310.pyc'
# extension module 'pygame._freetype' loaded from '/opt/coindicator/venv/lib/python3.10/site-packages/pygame/_freetype.cpython-310-x86_64-linux-gnu.so'
# extension module 'pygame._freetype' executed from '/opt/coindicator/venv/lib/python3.10/site-packages/pygame/_freetype.cpython-310-x86_64-linux-gnu.so'
import 'pygame._freetype' # <_frozen_importlib_external.ExtensionFileLoader object at 0x77d51075baf0>
import 'pygame.freetype' # <_frozen_importlib_external.SourceFileLoader object at 0x77d51075af20>
# clear builtins._

**Comment by greenozon** [comment]
Please provide your env (OS, etc) and steps your have executed,
also
please take into account a step from readme - 
```
Before reporting bugs or issues, please try removing/renaming the ~/.config/coindicator folder first.
```
